language: node_js
# Temporary workaround.
# Karma can't access the binaries on travis
# without root access.
sudo: required
node_js:
  - "4"
  - "6"
  - "8"
  - "9"

addons:
  # We put this back ONLY so Travis installs the required Linux graphical libraries
  chrome: stable

env:
  global:
    # Use TRAVIS_BUILD_DIR to guarantee the absolute path is correct
    - CHROME_BIN=$TRAVIS_BUILD_DIR/chrome-linux/chrome
  matrix:
    - NPM_SCRIPT=test:browserless

matrix:
  include:
    # Run browser tests only on one Node.js version to save time.
    - node_js: "8"
      env: NPM_SCRIPT=test:browser
      
before_install:
  # Download historically accurate Chromium ~v64 (Jan 2018)
  - wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F560467%2Fchrome-linux.zip?generation=1526957952075076&alt=media
  - unzip chrome-linux.zip
  # Ensure the extracted binary has execution permissions
  - chmod +x $TRAVIS_BUILD_DIR/chrome-linux/chrome

script:
  - npm run $NPM_SCRIPT